name:                haskell-admin-managed-functions
version:             0.1.0.0
github:              "martin-bednar/haskell-admin"
license:             MIT
author:              "Martin Bednar"
maintainer:          "bednam17@fit.cvut.cz"
copyright:           "2022 Martin Bednar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Managed Functions integration for Haskell Admin
category:            Haskell Admin, Managed Functions, Remote Management

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/martin-bednar/haskell-admin#readme>

dependencies:
- base >= 4.7 && < 5
- haskell-admin-core
- managed-functions
- managed-functions-http-connector
- servant-server

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  haskell-admin-managed-functions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-admin-managed-functions
    - hspec
    - hspec-wai
