name:                haskell-admin
version:             1.0.0.0
github:              "martin-bednar/haskell-admin"
license:             MIT
author:              "Martin Bednar"
maintainer:          "bednam17@fit.cvut.cz"
copyright:           "2022 Martin Bednar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:           Remote Management Platform for Haskell Applications
category:           Remote Management

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/martin-bednar/haskell-admin#readme>

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wmonomorphism-restriction
- -Wmissing-home-modules
- -Widentities
- -Wredundant-constraints
- -Wmissing-export-lists

dependencies:
- base >= 4.7 && < 5
- haskell-admin-core
- wai
- bytestring

library:
  source-dirs: src
