name:                haskell-admin-core
version:             1.0.0.0
github:              "martin-bednar/haskell-admin"
license:             MIT
author:              "Martin Bednar"
maintainer:          "bednam17@fit.cvut.cz"
copyright:           "2022 Martin Bednar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Core Modules of Haskell Admin
category:            Remote Management, Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/martin-bednar/haskell-admin#readme>

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wmonomorphism-restriction
- -Wmissing-home-modules
- -Widentities
- -Wredundant-constraints
- -Wmissing-export-lists

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- http-types
- servant
- servant-server
- wai
- wai-cors
- wai-middleware-bearer
- word8

library:
  source-dirs: src

tests:
  haskell-admin-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-admin-core
    - hspec
    - hspec-wai
    - http-types
    - wai-extra
